### ISSUE TITLE
python3 store_block_data.py -->null &

### ISSUE THREAD

**Issue by timmetje21** [trinity-project/trinity#19]
Hi fellow TNCers

Been trying to setup the node but i think(hope) am getting an easy error but as im new to ubuntu its quite hard....running desktop ubuntu 16.04. If correct its not letting me connect to localhost or something? hope someone can help

thanks
```
 File "/home/tim/.local/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/tim/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/tim/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/tim/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/tim/.local/lib/python3.5/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/tim/.local/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb2f08d1c50>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/tim/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/tim/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=20332): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2f08d1c50>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "store_block_data.py", line 162, in <module>
    chain_block_count=getblockcount()
  File "store_block_data.py", line 134, in getblockcount
    res = requests.post(NEOCLIURL, headers=headers, json=data).json()
  File "/home/tim/.local/lib/python3.5/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/tim/.local/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/tim/.local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tim/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/tim/.local/lib/python3.5/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=20332): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2f08d1c50>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by timmetje21** [comment]
thx for helping!
when i submit the command dotnet neo-cli.dll /rpc, its seem to be working fine
but when i use the command 'show node' its giving me:
neo> show state
Height: 0/4477/42000, Nodes: 0

output after using 'netstat -apn'

(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      -               
tcp        0      0 10.0.2.15:33344         192.30.253.125:443      ESTABLISHED 4802/firefox    
tcp6       0      0 ::1:631                 :::*                    LISTEN      -               
udp        0      0 0.0.0.0:34639           0.0.0.0:*                           -               
udp        0      0 127.0.1.1:53            0.0.0.0:*                           -               
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -               
udp        0      0 0.0.0.0:631             0.0.0.0:*                           -               
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -               
udp6       0      0 :::58984                :::*                                -               
udp6       0      0 :::5353                 :::*                                -               
raw6       0      0 :::58                   :::*                    7           -

**Comment by pigxo** [comment]
while using /rpc  launch the neo-cli there will be one socket listening the port 20332(neo testnet， mainnet is 10332) such as:
`$ netstat -apn|grep 10332
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:10332           0.0.0.0:*               LISTEN      3475/dotnet    `

so would you please try again? submit the command "dotnet neo-cli.dll /rpc", then launch another terminate to submit netstate, if still not find the 20332, try disable the firewall using "ufw disable", if it worked , maybe you will wait the neo sync the block, 
`neo> show state
Height: 0/1231166/1231166, Nodes: 3`

**Comment by timmetje21** [comment]
```
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:10333           0.0.0.0:*               LISTEN      1964/dotnet     
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -               
tcp        0      1 10.0.2.15:49013         195.201.22.35:10333     SYN_SENT    1964/dotnet     
tcp    16175      0 10.0.2.15:50365         101.132.67.230:10333    ESTABLISHED 1964/dotnet     
tcp    18898      0 10.0.2.15:39901         47.94.164.49:10333      ESTABLISHED 1964/dotnet     
tcp        0      1 10.0.2.15:56747         13.125.223.245:10333    SYN_SENT    1964/dotnet     
tcp        0      1 10.0.2.15:33173         61.104.121.130:10333    SYN_SENT    1964/dotnet     
tcp        0      1 10.0.2.15:51467         139.218.142.154:10333   SYN_SENT    1964/dotnet     
tcp        0      1 10.0.2.15:58601         40.125.163.212:10333    SYN_SENT    1964/dotnet     
tcp6       0      0 ::1:631                 :::*                    LISTEN      -               
tcp6       0      0 :::10334                :::*                    LISTEN      1964/dotnet     
udp        0      0 0.0.0.0:54749           0.0.0.0:*                           -               
udp        0      0 127.0.1.1:53            0.0.0.0:*                           -               
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -               
udp        0      0 0.0.0.0:40536           0.0.0.0:*                           -               
udp        0      0 0.0.0.0:631             0.0.0.0:*                           -               
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -               
udp6       0      0 :::5353                 :::*                                -               
udp6       0      0 :::55053                :::*                                -               
raw6       0      0 :::58                   :::*                    7           -       
```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=20332): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cc148e9e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
its not getting easier :s 
thx for the help tho

**Comment by pigxo** [comment]
very strange,  it still seems the RPC service not startup, would you please show me the neo-cli configure file <config.json>  and submit the command history to show me the result? thanks

**Comment by timmetje21** [comment]
sir, it is possible from a virtual machine right?
here u go

tim@tim-VirtualBox:~$ Downloads/neo cli
bash: Downloads/neo: No such file or directory
tim@tim-VirtualBox:~$ cd Downloads/neo-cli
tim@tim-VirtualBox:~/Downloads/neo-cli$ dotnet neo-cli.dll /rpg
NEO-CLI Version: 2.7.1.0

neo> 


```
﻿{
  "ApplicationConfiguration": {
    "Paths": {
      "Chain": "ChainTestNet"
    },
    "P2P": {
      "Port": 20333,
      "WsPort": 20334
    },
    "RPC": {
      "Port": 20332,
      "SslCert": "",
      "SslCertPassword": ""
    }
  }
}
```

**Comment by pigxo** [comment]
here
`tim@tim-VirtualBox:/Downloads/neo-cli$ dotnet neo-cli.dll /rpg` 
it should be rpc not rpg

**Comment by timmetje21** [comment]
ur the man....gosh i feel....bad....

**Comment by pigxo** [comment]
you can get the off-line data from http://static.neo.org/client/chain.acc.zip, then unzip it into TestChain folder

**Comment by timmetje21** [comment]
I managed to setup the wallet, thx for the help.
Altho i kept getting an error 'Failed building wheel for scrypt', not only me but there were others
aswel. I have fixed it by 
apt-get install libssl-dev

Not sure if this error is common, if it does it should be included in the trinity user guide!

**Comment by timmetje21** [comment]
@malcolmturnballs 
i have made an user friendly guide. 
https://medium.com/@timajax5/user-friendly-tutorial-setting-up-trinity-service-node-deployment-with-ubuntu-16-04-34d566077dcc
Not sure if its any helpfull but for the not-so-tech people could be helpfull

**Comment by malcolmturnballs** [comment]
On Windows:
Had this step running for hours - still nothing :(
The results of show state:
Height: 0/1244133/1244133, Nodes: 10

Got this error when I stopped running Neo:
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=2
0332): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.
connection.HTTPConnection object at 0x041BE3F0>: Failed to establish a new conne
ction: [WinError 10061] No connection could be made because the target machine a
ctively refused it',))

**Comment by timmetje21** [comment]
Mmm looks like the same error i had, u sure u run the /rpc command?

**Comment by malcolmturnballs** [comment]
yeah definitely
with 'show state', is it okay that one of the numbers are still showing 0? (0 / 1244133 / 1244133)
